import Head from "next/head";
import { useContext, useEffect } from "react";

import { ShoppingCartContext } from "@/contexts/ShoppingCartContext";

export default function ShoppingCart() {
  const { getProducts } = useContext(ShoppingCartContext);

  useEffect(() => {
    const products = getProducts();
    console.log(products)
  }, []);

  return (
    <>
      <Head>
        <title>Imagineshop - Shopping Cart</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  );
}
