import Head from "next/head";
import styled from "styled-components";

import Banner from "@/components/Banner";
import BannerImage from "../../public/images/BANNER01.png";
import Products from "@/components/Products";
import { GetServerSideProps } from "next";

export const getServerSideProps: GetServerSideProps = async () => {
  const api = "https://imagineshopapi.fly.dev";
  const result = await fetch(`${api}/products`);
  const data = await result.json();
  data.forEach((product: any) => {
    product.image = `${api}/uploads/${product.fileName}`;
    product.formattedPrice = (new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' })).format(product.price)
    product.splitPrice = (new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' })).format(product.price/10)
  })
  return {
    props: {
      productsApi: data
    }
  }
}

export default function Home({ productsApi }: any) {
  return (
    <>
      <Head>
        <title>Imagineshop - Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.ico" />
      </Head>

      <Main>
        <Banner image={BannerImage} width={1140} height={325} />
        <Products products={productsApi}></Products>
      </Main>
    </>
  );
}

const Main = styled.main`
  min-height: 59vh;
`;
